name: myitihas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.1.0
  go_router: ^17.0.1
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4
  google_fonts: ^6.3.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  injectable: ^2.7.1
  fpdart: ^1.2.0
  talker: ^5.1.9
  talker_flutter: ^5.1.9
  talker_bloc_logger: ^5.1.9
  flutter_screenutil: ^5.9.3
  animations: ^2.1.1
  slang: ^4.11.1
  slang_flutter: ^4.11.0
  intl: ^0.20.2
  dio: ^5.9.0
  talker_dio_logger: ^5.1.9
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  equatable: ^2.0.7
  internet_connection_checker_plus: ^2.9.1
  get_it: ^9.2.0
  timeago: ^3.7.1
  smooth_page_indicator: ^2.0.1
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0

  sizer: ^3.1.3
  getwidget: ^7.0.0
  sqflite: ^2.4.2
  supabase_flutter: ^2.5.6
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.10.4

  # Routing (code generation)
  go_router_builder: ^4.1.3

  # DI / Models / Serialization
  freezed:
    git:
      url: https://github.com/AmanSikarwar/freezed.git
      path: packages/freezed
  json_serializable: ^6.11.3
  injectable_generator: ^2.11.1

  # i18n + storage
  slang_build_runner: ^4.11.0
  hive_ce_generator: ^1.10.1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - docs/dataset.json
